Added `linode` and `lin` alias
linode/linode-cli pull request #414
Opened 2023-03-21 17:30 UTC by ezilber-akamai

## 📝 Description

Added `linode` and `lin` alias for the linode-cli. Users can now call all existing `linode-cli` commands using the shorthand alias.

## ✔️ How to Test

`make testunit`

2023-03-21 17:46 UTC, jriddle-linode approved these changes

2023-03-21 18:06 UTC, zliang-akamai commented on setup.py
> +)
Can you add a blank line at the end of the file? To get rid of GitHub warning.

2023-03-21 18:06 UTC, zliang-akamai approved these changes

2023-03-21 20:27 UTC, lgarber-akamai requested changes
Great work so far!

2023-03-21 20:27 UTC, lgarber-akamai commented on lin.sh
> +# This is a generated file by Linode-CLI! Do not modify!
You might need to add `lin.sh` and `linode.sh` to `.gitignore` 👍

2023-03-21 20:27 UTC, lgarber-akamai commented on linodecli/completion.py
> +complete -c linode -n "not __fish_seen_subcommand_from $subcommands" -x -a '$subcommands --help'
The corresponding unit tests may need to be adjusted to expect these as a part of the output

2023-03-22 17:47 UTC, lgarber-akamai approved these changes
Great work!

2023-03-22 18:11 UTC, merged