test: Add workflow for Windows
linode/linode-cli pull request #461
Opened 2023-05-24 19:56 UTC by ykim-1

## 📝 Description

**What does this PR do and why is this change necessary?**

## ✔️ How to Test

Unit tests are executed upon push

Integration tests can be ran using /wintest sha=... command on GH

## 📷 Preview

**If applicable, include a screenshot or code snippet of this change. Otherwise, please remove this section.**

2023-05-24 21:35 UTC, ykim-1 commented
/wintest sha=f8bb8e37ec60a73fa98282c14930d421e4dd3f94

2023-05-24 21:39 UTC, ykim-1 commented
/wintest sha=fa92e696db88bc9b7b08d934f0f37f01ae92fcf3

2023-05-25 14:16 UTC, lgarber-akamai requested changes
Great work! Just one small code suggestion and we should be good to go

2023-05-30 17:34 UTC, lgarber-akamai approved these changes

2023-05-31 15:56 UTC, zliang-akamai commented on setup.py
> +
Let me digging into this. I think Windows's shell environment can be complicated and we can't assume everybody uses the mingw64 inside Git bundle... If it's too complicated we might want to not implement the auto completion on windows.

2023-05-31 16:42 UTC, zliang-akamai commented on tests/unit/conftest.py
> +def get_platform_os_type():
Actually, we can skip tests in win by a decorator.
https://docs.pytest.org/en/7.1.x/how-to/skipping.html#skip-all-test-functions-of-a-class-or-module

2023-05-31 20:34 UTC, zliang-akamai approved these changes

2023-06-01 15:16 UTC, merged